class Constants():
    TAG_NAME_MAX_LENGTH = 256
    TAG_SLUG_MAX_LENGTH = 256
    INGREDIENT_NAME_MAX_LENGTH = 256
    INGREDIENT_UNIT_MAX_LENGTH = 10
    RECIPE_NAME_MAX_LENGTH = 256
    COOKING_TIME_MIN = 1
    COOKING_TIME_MAX = 32000
    AMOUNT_MIN = 1
    AMOUNT_MAX = 32000